### PR TITLE
Simplified JSON manifest build process

### PR DESCRIPTION
**Pull request by emirotin**
Signed-off-by: Eugene Mirotin <eugene@resin.io>

This implements https://github.com/resin-os/resin-yocto-scripts/pull/31, will be updated properly after that PR is merged.

### CODE REVIEW

**Comment by emirotin** [comment]
Gents, could you please have a look why this fails? 

The line that throws an error is `npm install --production --silent >/dev/null || quit "ERROR - Please install the 'npm' package before running this script."`

The entire process works fine on my machine.

**Comment by emirotin** [comment]
OK we have the ubuntu-provided packages for nodejs and npm, they are very outdated. I'll check how to update them.

**Comment by floion** [comment]
LGTM

**Comment by emirotin** [comment]
It failed again. @agherzan any chance you did pull the older build image?

**Comment by agherzan** [comment]
@emirotin on what build machine?

**Comment by emirotin** [comment]
Oh hm, now it's fixed. So it'd hit another builder?

**Comment by emirotin** [comment]
It failed on build4, then succeeded on build8.

**Comment by agherzan** [comment]
I only fixed 7 and 8 at that point (cause those were the ones you hit). I updated 4, 5 ,6 too.

**Comment by emirotin** [comment]
👍

**Pull request merged**
