### PR TITLE
Release v1.30.1

### PR DESCRIPTION
**Pull request by floion**

### CODE REVIEW

**Comment by imrehg** [comment]
@willnewton how can we see if the emmc patches are included in this? 

@floion would be good to have some more info, not "head" but specific sha or tag in the changelog to know what's the version that's actually included, what do you think?

**Comment by willnewton** [comment]
@imrehg it should be merged into the beagleboard linux tree. I can't actually find the tag we use in the upstream tree, the closest I can get is 4.9.38-ti-rt-r48 which contains the relevant commit 555e9fb067cbdd4cd96422dd5a96ab8a89de3f31

**Comment by floion** [comment]
@imrehg I don't know how relevant is to include that info for resin-yocto-scripts. Considering we don't version that repository, and it's mainly build scripts there, I would say it's overhead to always specify some revision which you can anyway see when you checkout the resin-<board> repository

**Comment by imrehg** [comment]
@floion I mean that from this changelog wouldn't really know what is pulled in. But anyways, it's not a blocker just nice to have, thanks!

**Pull request merged**
