### PR TITLE
Allow HDMI disable and allow the use of on-board wireles

### PR DESCRIPTION
**Pull request by telphan**
@agherzan @floion

### CODE REVIEW

**Comment by telphan** [comment]
Related to #10

**Comment by agherzan** [comment]
ok to test

**Comment by agherzan** [comment]
LGTM but needs conflicts fixes.

**Comment by agherzan** [comment]
Typo in commit log of a commit: "enumarate"

**Comment by floion** [comment]
LGTM

**Comment by agherzan** [comment]
LGTM

**Pull request merged**
