### PR TITLE
Generate a bmap file for the resin-sdcard image

### PR DESCRIPTION
**Pull request by michal-mazurek**

### CODE REVIEW

**Comment by michal-mazurek** [comment]
connect https://github.com/resin-os/resinos/issues/163

**Comment by floion** [comment]
@michal-mazurek can you redo this commit against the master branch please?

**Comment by floion** [comment]
ping @michal-mazurek ?

**Comment by agherzan** [comment]
@michal-mazurek ping on this please.

**Comment by michal-mazurek** [comment]
Replaced by https://github.com/resin-os/resin-beaglebone/pull/76

**Pull request closed without merging**
